services:
  openvpn_main_udp:
    build:
      context: ./openvpn
      dockerfile: Dockerfile
    container_name: openvpn_main_udp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - openvpn_main_data_udp:/openvpn-main-udp
    ports:
      - "1195:1195/udp"
    environment:
      DATA_DIR: /openvpn-main-udp
      PORT: "1195"
      PROTO: udp
      MGMT_PORT: "5095"
      DNS1: 8.8.8.8
      DNS2: 8.8.4.4
      VPN_SUBNET: 10.51.28.0
      VPN_NETMASK: 255.255.255.0
    networks:
      - backend_network

volumes:
  openvpn_main_data_udp:

networks:
  backend_network:
    external: true
    name: openvpngatemonitor_backend_network